import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DarkModeToggle from "./Components/DarkMode";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster toastOptions={{ className: "sonner"}} position="top-right" duration={5000}/>
        <SessionProvider>
        <div className=" bg-white dark:bg-gray-900 text-black dark:text-white transition-colors duration-300 ">
        
        {children}
        </div>
        </SessionProvider>

      </body>
    </html>
  );
}
